[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
# linker = "x86_64-unknown-linux-musl-gcc"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
